import { createInsertSchema } from "drizzle-zod";
import type { z } from "zod";
import { illustrations } from "@/db/schema/index";
import type { selectAllIllustrations } from "@/db/queries/index";

// Schema for inserting a user - can be used to validate API requests
export const insertIllustrationsSchema = createInsertSchema(illustrations);

// Define and export a type for the schema created by the insertDocumentsSchema function.
export type InsertIllustrations = z.infer<typeof insertIllustrationsSchema>;

// Define and export a type based on the success result of the All Documents function.
export type Illustration = NonNullable<
  Awaited<ReturnType<typeof selectAllIllustrations>>["illustrations"]
>[number];

export interface InsurancePolicy {
  SUNL: {
    Year: number;
    Age: number;
    "Total guaranteed yearly premium": number;
    "Total guaranteed annualized premium": number;
    "Total guaranteed monthly premium": number;
    "Total annualized premium (Current rate)": number;
    "Total annualized premium (Current rate minus 1%)": number;
    "Total annualized premium (Current rate minus 2%)": number;
    "Guaranteed cash value": number;
    "Cash surrender value (Current rate)": number;
    "Cash surrender value (Current rate minus 1%)": number;
    "Cash surrender value (Current rate minus 2%)": number;
    "Base insurance amount": number;
    "Guaranteed insurance amount": number;
    "Total death benefit (Current rate)": number;
    "Total death benefit (Current rate minus 1%)": number;
    "Total death benefit (Current rate minus 2%)": number;
    "Annual dividend (Current rate)": number;
    "Annual dividend (Current rate minus 1%)": number;
    "Annual dividend (Current rate minus 2%)": number;
    "Paid up additional insurance (Current rate)": number;
    "Paid up additional insurance (Current rate minus 1%)": number;
    "Paid up additional insurance (Current rate minus 2%)": number;
    "One year term insurance (Current rate)": number;
    "One year term insurance (Current rate minus 1%)": number;
    "One year term insurance (Current rate minus 2%)": number;
    "Paid up additional insurance cash value (Current rate)": number;
    "Paid up additional insurance cash value (Current rate minus 1%)": number;
    "Paid up additional insurance cash value (Current rate minus 2%)": number;
    "Dividends on deposits (Current rate)": number;
    "Dividends on deposits (Current rate minus 1%)": number;
    "Dividends on deposits (Current rate minus 2%)": number;
    "Dividends paid in cash (Current rate)": number;
    "Dividends paid in cash (Current rate minus 1%)": number;
    "Dividends paid in cash (Current rate minus 2%)": number;
    "Premiums paid by dividends (Current rate)": number;
    "Premiums paid by dividends (Current rate minus 1%)": number;
    "Premiums paid by dividends (Current rate minus 2%)": number;
    "Base plan premium": number;
    "Policy Fee": number;
    "Premiums paid by client (Current rate)": number;
    "Premiums paid by client (Current rate minus 1%)": number;
    "Premiums paid by client (Current rate minus 2%)": number;
    "Plus premium payment (Current rate)": number;
    "Plus premium payment (Current rate minus 1%)": number;
    "Plus premium payment (Current rate minus 2%)": number;
    "Optional benefits premium": number;
    "Term benefit 1 premium": number;
    "Term benefit 1 Death benefit": number;
    "Term benefit 2 premium": number;
    "Term benefit 2 Death benefit": number;
    "Term benefit 3 premium": number;
    "Term benefit 3 Death benefit": number;
    "Term benefit 4 premium": number;
    "Term benefit 4 Death benefit": number;
    "Person 1 ADB premium": number;
    "Person 2 ADB premium": number;
    "Person 1 TDW premium": number;
    "Person 2 TDW premium": number;
    "GIB premium": number;
    "CTB premium": number;
    "BVPB premium": number;
    "Owner waiver premium": number;
    "NCPI (Current rate)": number;
    "NCPI (Current rate minus 1%)": number;
    "NCPI (Current rate minus 2%)": number;
    "ACB (Current rate)": number;
    "ACB (Current rate minus 1%)": number;
    "ACB (Current rate minus 2%)": number;
    "CDA credit (Current rate)": number;
    "CDA Credit (Current rate minus 1%)": number;
    "CDA Credit (Current rate minus 2%)": number;
    "Marginal tax rate": number;
    "Before tax policy loan (Current rate)": number;
    "Before tax policy loan (Current rate minus 1%)": number;
    "Before tax policy loan (Current rate minus 2%)": number;
    "Taxable portion of policy loan (Current rate)": number;
    "Taxable portion of policy loan (Current rate minus 1%)": number;
    "Taxable portion of policy loan (Current rate minus 2%)": number;
    "Tax on policy loan (Current rate)": number;
    "Tax on policy loans (Current rate minus 1%)": number;
    "Tax on policy loans (Current rate minus 2%)": number;
    "After tax policy loan (Current rate)": number;
    "After tax policy loan (Current rate minus 1%)": number;
    "After tax policy loan (Current rate minus 2%)": number;
    "Interest on policy loan (Current rate)": number;
    "Interest on policy loan (Current rate minus 1%)": number;
    "Interest on policy loan (Current rate minus 2%)": number;
    "Policy loan balance (Current rate)": number;
    "Policy loan balance (Current rate minus 1%)": number;
    "Policy loan balance (Current rate minus 2%)": number;
    "Before tax withdrawal (Current rate)": number;
    "Before tax withdrawal (Current rate minus 1%)": number;
    "Before tax withdrawal (Current rate minus 2%)": number;
    "Taxable portion of withdrawal (Current rate)": number;
    "Taxable portion of withdrawal (Current rate minus 1%)": number;
    "Taxable portion of withdrawal (Current rate minus 2%)": number;
    "After tax withdrawal (Current rate)": number;
    "After tax withdrawal (Current rate minus 1%)": number;
    "After tax withdrawal (Current rate minus 2%)": number;
    "Tax on withdrawals (Current rate)": number;
    "Tax on withdrawals (Current rate minus 1%)": number;
    "Tax on withdrawals (Current rate minus 2%)": number;
    "Tax on CSV (Current rate)": number;
    "Tax on CSV (Current rate minus 1%)": number;
    "Tax on CSV (Current rate minus 2%)": number;
    "Taxable portion of the CSV (Current rate)": number;
    "Taxable Portion of the CSV (Current rate minus 1%)": number;
    "Taxable Portion of the CSV (Current rate minus 2%)": number;
    "CSV after tax (Current rate)": number;
    "CSV after tax (Current rate minus 1%)": number;
    "CSV after tax (Current rate minus 2%)": number;
    "Increase in CSV (Current rate)": number;
    "Increase in CSV (Current rate minus 1%)": number;
    "Increase in CSV  (Current rate minus 2%)": number;
    "Taxable Portion of Dividends (Current rate)": number;
    "Taxable Portion of Dividends (Current rate minus 1%)": number;
    "Taxable Portion of Dividends (Current rate minus 2%)": number;
    "Tax on Dividends (Current rate)": number;
    "Tax on Dividends (Current rate minus 1%)": number;
    "Tax on Dividends (Current rate minus 2%)": number;
    "Tax on Dividends on deposit (Current rate)": number;
    "Tax on Dividends on deposit (Current rate minus 1%)": number;
    "Tax on Dividends on deposit (Current rate minus 2%)": number;
    "Total IRR on death benefit (Current rate)": number;
    "Total IRR on death benefit (Current rate minus 1%)": number;
    "Total IRR on death benefit (Current rate minus 2%)": number;
    "NAAR (Current rate)": number;
    "NAAR (Current rate minus 1%)": number;
    "NAAR (Current rate minus 2%)": number;
  };
}
